### ISSUE TITLE
Running Pi Presents GTK 

### ISSUE THREAD

**Issue by HT1929** [KenT2/pipresents-gtk#1]
I'm currently trying to use PiPresents and I have RPi OS Bookworm (32 bit) installed and was able to install all the packages on the instruction page. When running `python pipresents.py` , the error screen do not pop up with an OK button. Instead it gave me this error in the terminal:

STARTUP ERROR: Profile not specified with the commands -p option
error exit

And after downloading the example profiles, I could not run the example profile either. In this case, I received this error message:

STARTUP ERROR: Failed to find requested profile: /home/pi/pp_home/pp_profiles/pp_mediashow_1p6
error exit

**Comment by KenT2** [comment]
Your first problem. Yes there is an error in the Readme. It should say a message is displayed in the terminal window. I will modify it.

Your second problem. I looks like you have not  installed the examples correctly. You should have a directory:
/home/pi/pp_home/pp_profiles/pp_mediashow_1p6 with files in it pp_showlist.json and mymediashow.json

**Comment by HT1929** [comment]
Figured it out. Turns out I had pp_home inside another directory called pp_home which was why the examples couldn't be accessed. Thank you for your help!
